### ISSUE TITLE
如何加入翻譯？

### ISSUE THREAD

**Issue by ccwang002** [python-doc-tw/python-doc-tw#16]
最近有空可以幫忙翻譯，不知道現在團隊是怎麼分配要翻譯的頁面？有沒有翻譯的流程在 wiki 上可以參考？

謝謝！

**Comment by adrianliaw** [comment]
@ccwang002 感謝提醒！！我正在把翻譯的工作流程說明補齊（今天晚上比較有空可以把 wiki 的部分補上），但基本上主要的改變是整個翻譯流程以 GitHub 為主，參考法文翻譯團隊的方式，如果要翻譯的話請開一個 issue 並註明正在翻譯的頁面，並且把 issue assign 給自己。

不過翻譯者要做的事情比以前複雜點，基本上是走標準的 GitHub Flow，fork -> branch -> translate -> commit -> pull request 這樣。Transifex 在這邊是擔任一個翻譯工具的角色，也可以用 PoEdit 等離線翻譯工具代替。但如果是用 Transifex 的話，我前幾天有寫一個[小小的 script](https://github.com/python-doc-tw/python-docs-zh-tw/blob/3.6/txpull) 比較方便整合進目前的專案，使用方法是 `$ ./txpull <local po file path>`。

上面的資訊很不完整XD 我稍晚把正規流程再補上！這個 issue 先保持 open
